// src/State/SGPA/ActionType.js

export const GET_SGPA_REQUEST = "GET_SGPA_REQUEST";
export const GET_SGPA_SUCCESS = "GET_SGPA_SUCCESS";
export const GET_SGPA_FAILURE = "GET_SGPA_FAILURE";

export const ADD_SGPA_REQUEST = "ADD_SGPA_REQUEST";
export const ADD_SGPA_SUCCESS = "ADD_SGPA_SUCCESS";
export const ADD_SGPA_FAILURE = "ADD_SGPA_FAILURE";

export const UPDATE_SGPA_REQUEST = "UPDATE_SGPA_REQUEST";
export const UPDATE_SGPA_SUCCESS = "UPDATE_SGPA_SUCCESS";
export const UPDATE_SGPA_FAILURE = "UPDATE_SGPA_FAILURE";

export const DELETE_SGPA_REQUEST = "DELETE_SGPA_REQUEST";
export const DELETE_SGPA_SUCCESS = "DELETE_SGPA_SUCCESS";
export const DELETE_SGPA_FAILURE = "DELETE_SGPA_FAILURE";
