export const GET_RESOURCE_REQUEST = "GET_RESOURCE_REQUEST";
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const GET_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE";

export const GET_RESOURCE_BY_TYPE_REQUEST = "GET_RESOURCE_BY_TYPE_REQUEST";
export const GET_RESOURCE_BY_TYPE_SUCCESS = "GET_RESOURCE_BY_TYPE_SUCCESS";
export const GET_RESOURCE_BY_TYPE_FAILURE = "GET_RESOURCE_BY_TYPE_FAILURE";

export const GET_RESOURCE_BY_SUBJECT_REQUEST = "GET_RESOURCE_BY_SUBJECT_REQUEST";
export const GET_RESOURCE_BY_SUBJECT_SUCCESS = "GET_RESOURCE_BY_SUBJECT_SUCCESS";
export const GET_RESOURCE_BY_SUBJECT_FAILURE = "GET_RESOURCE_BY_SUBJECT_FAILURE";

export const CREATE_RESOURCE_REQUEST = "CREATE_RESOURCE_REQUEST";
export const CREATE_RESOURCE_SUCCESS = "CREATE_RESOURCE_SUCCESS";
export const CREATE_RESOURCE_FAILURE = "CREATE_RESOURCE_FAILURE";

export const DELETE_RESOURCE_REQUEST = "DELETE_RESOURCE_REQUEST";
export const DELETE_RESOURCE_SUCCESS = "DELETE_RESOURCE_SUCCESS";
export const DELETE_RESOURCE_FAILURE = "DELETE_RESOURCE_FAILURE";

export const UPDATE_RESOURCE_REQUEST = "UPDATE_RESOURCE_REQUEST";
export const UPDATE_RESOURCE_SUCCESS = "UPDATE_RESOURCE_SUCCESS";
export const UPDATE_RESOURCE_FAILURE = "UPDATE_RESOURCE_FAILURE";