
export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_FAILURE = "GET_SUBJECT_FAILURE";

export const GET_SUBJECT_BY_ID_REQUEST = "GET_SUBJECT_BY_ID_REQUEST";
export const GET_SUBJECT_BY_ID_SUCCESS = "GET_SUBJECT_BY_ID_SUCCESS";
export const GET_SUBJECT_BY_ID_FAILURE = "GET_SUBJECT_BY_ID_FAILURE";

export const GET_SUBJECT_BY_BRANCH_REQUEST ="GET_SUBJECT_BY_BRANCH_REQUEST";
export const GET_SUBJECT_BY_BRANCH_SUCCESS ="GET_SUBJECT_BY_BRANCH_SUCCESS";
export const GET_SUBJECT_BY_BRANCH_FAILURE ="GET_SUBJECT_BY_BRANCH_FAILURE";

export const CREATE_SUBJECT_REQUEST = "CREATE_SUBJECT_REQUEST";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_FAILURE = "CREATE_SUBJECT_FAILURE";

export const UPDATE_SUBJECT_REQUEST = "UPDATE_SUBJECT_REQUEST";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_FAILURE = "UPDATE_SUBJECT_FAILURE";

export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAILURE = "DELETE_SUBJECT_FAILURE";