// FETCH
export const GET_ATTENDANCE_REQUEST = "GET_ATTENDANCE_REQUEST";
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS";
export const GET_ATTENDANCE_FAILURE = "GET_ATTENDANCE_FAILURE";

// CREATE
export const ADD_ATTENDANCE_REQUEST = "ADD_ATTENDANCE_REQUEST";
export const ADD_ATTENDANCE_SUCCESS = "ADD_ATTENDANCE_SUCCESS";
export const ADD_ATTENDANCE_FAILURE = "ADD_ATTENDANCE_FAILURE";

// UPDATE
export const UPDATE_ATTENDANCE_REQUEST = "UPDATE_ATTENDANCE_REQUEST";
export const UPDATE_ATTENDANCE_SUCCESS = "UPDATE_ATTENDANCE_SUCCESS";
export const UPDATE_ATTENDANCE_FAILURE = "UPDATE_ATTENDANCE_FAILURE";

// DELETE
export const DELETE_ATTENDANCE_REQUEST = "DELETE_ATTENDANCE_REQUEST";
export const DELETE_ATTENDANCE_SUCCESS = "DELETE_ATTENDANCE_SUCCESS";
export const DELETE_ATTENDANCE_FAILURE = "DELETE_ATTENDANCE_FAILURE";
